<?php return array (
  'c610c9ea5e71690e7e02f9aba8eb1df7' => 
  array (
    'files' => 
    array (
      0 => '/var/www/mnbsl/core/components/login/model/recaptcha/recaptcha.class.php',
      1 => '/var/www/mnbsl/core/components/login/model/recaptcha',
      2 => '/var/www/mnbsl/core/components/login/model/stopforumspam/stopforumspam.class.php',
      3 => '/var/www/mnbsl/core/components/login/model/stopforumspam',
      4 => '/var/www/mnbsl/core/components/login/model/login/lgnvalidator.class.php',
      5 => '/var/www/mnbsl/core/components/login/model/login/lgnhooks.class.php',
      6 => '/var/www/mnbsl/core/components/login/model/login/login.class.php',
      7 => '/var/www/mnbsl/core/components/login/model/login',
      8 => '/var/www/mnbsl/core/components/login/model',
      9 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnforgotpassemail.chunk.tpl',
      10 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnforgotpasssenttpl.chunk.tpl',
      11 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnactivateemailtpl.chunk.tpl',
      12 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnforgotpasstpl.chunk.tpl',
      13 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnchangepassword.chunk.tpl',
      14 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnresetpasstpl.chunk.tpl',
      15 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnlogintpl.chunk.tpl',
      16 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnupdateprofile.chunk.tpl',
      17 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnerrtpl.chunk.tpl',
      18 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnregisterformtpl.chunk.tpl',
      19 => '/var/www/mnbsl/core/components/login/elements/chunks/lgnlogouttpl.chunk.tpl',
      20 => '/var/www/mnbsl/core/components/login/elements/chunks',
      21 => '/var/www/mnbsl/core/components/login/elements/snippets/profile.snippet.php',
      22 => '/var/www/mnbsl/core/components/login/elements/snippets/forgotpassword.snippet.php',
      23 => '/var/www/mnbsl/core/components/login/elements/snippets/confirmregister.snippet.php',
      24 => '/var/www/mnbsl/core/components/login/elements/snippets/changepassword.snippet.php',
      25 => '/var/www/mnbsl/core/components/login/elements/snippets/updateprofile.snippet.php',
      26 => '/var/www/mnbsl/core/components/login/elements/snippets/resetpassword.snippet.php',
      27 => '/var/www/mnbsl/core/components/login/elements/snippets/register.snippet.php',
      28 => '/var/www/mnbsl/core/components/login/elements/snippets/login.snippet.php',
      29 => '/var/www/mnbsl/core/components/login/elements/snippets/isloggedin.snippet.php',
      30 => '/var/www/mnbsl/core/components/login/elements/snippets',
      31 => '/var/www/mnbsl/core/components/login/elements',
      32 => '/var/www/mnbsl/core/components/login/.DS_Store',
      33 => '/var/www/mnbsl/core/components/login/lexicon/de/changepassword.inc.php',
      34 => '/var/www/mnbsl/core/components/login/lexicon/de/properties.inc.php',
      35 => '/var/www/mnbsl/core/components/login/lexicon/de/forgotpassword.inc.php',
      36 => '/var/www/mnbsl/core/components/login/lexicon/de/updateprofile.inc.php',
      37 => '/var/www/mnbsl/core/components/login/lexicon/de/default.inc.php',
      38 => '/var/www/mnbsl/core/components/login/lexicon/de/register.inc.php',
      39 => '/var/www/mnbsl/core/components/login/lexicon/de/recaptcha.inc.php',
      40 => '/var/www/mnbsl/core/components/login/lexicon/de/profile.inc.php',
      41 => '/var/www/mnbsl/core/components/login/lexicon/de',
      42 => '/var/www/mnbsl/core/components/login/lexicon/ru/forgotpassword.inc.php',
      43 => '/var/www/mnbsl/core/components/login/lexicon/ru/updateprofile.inc.php',
      44 => '/var/www/mnbsl/core/components/login/lexicon/ru/default.inc.php',
      45 => '/var/www/mnbsl/core/components/login/lexicon/ru/register.inc.php',
      46 => '/var/www/mnbsl/core/components/login/lexicon/ru',
      47 => '/var/www/mnbsl/core/components/login/lexicon/.DS_Store',
      48 => '/var/www/mnbsl/core/components/login/lexicon/fr/changepassword.inc.php',
      49 => '/var/www/mnbsl/core/components/login/lexicon/fr/properties.inc.php',
      50 => '/var/www/mnbsl/core/components/login/lexicon/fr/forgotpassword.inc.php',
      51 => '/var/www/mnbsl/core/components/login/lexicon/fr/updateprofile.inc.php',
      52 => '/var/www/mnbsl/core/components/login/lexicon/fr/default.inc.php',
      53 => '/var/www/mnbsl/core/components/login/lexicon/fr/register.inc.php',
      54 => '/var/www/mnbsl/core/components/login/lexicon/fr/recaptcha.inc.php',
      55 => '/var/www/mnbsl/core/components/login/lexicon/fr/profile.inc.php',
      56 => '/var/www/mnbsl/core/components/login/lexicon/fr',
      57 => '/var/www/mnbsl/core/components/login/lexicon/nl/changepassword.inc.php',
      58 => '/var/www/mnbsl/core/components/login/lexicon/nl/properties.inc.php',
      59 => '/var/www/mnbsl/core/components/login/lexicon/nl/forgotpassword.inc.php',
      60 => '/var/www/mnbsl/core/components/login/lexicon/nl/updateprofile.inc.php',
      61 => '/var/www/mnbsl/core/components/login/lexicon/nl/default.inc.php',
      62 => '/var/www/mnbsl/core/components/login/lexicon/nl/register.inc.php',
      63 => '/var/www/mnbsl/core/components/login/lexicon/nl/recaptcha.inc.php',
      64 => '/var/www/mnbsl/core/components/login/lexicon/nl/profile.inc.php',
      65 => '/var/www/mnbsl/core/components/login/lexicon/nl',
      66 => '/var/www/mnbsl/core/components/login/lexicon/en/changepassword.inc.php',
      67 => '/var/www/mnbsl/core/components/login/lexicon/en/properties.inc.php',
      68 => '/var/www/mnbsl/core/components/login/lexicon/en/forgotpassword.inc.php',
      69 => '/var/www/mnbsl/core/components/login/lexicon/en/updateprofile.inc.php',
      70 => '/var/www/mnbsl/core/components/login/lexicon/en/default.inc.php',
      71 => '/var/www/mnbsl/core/components/login/lexicon/en/register.inc.php',
      72 => '/var/www/mnbsl/core/components/login/lexicon/en/recaptcha.inc.php',
      73 => '/var/www/mnbsl/core/components/login/lexicon/en/profile.inc.php',
      74 => '/var/www/mnbsl/core/components/login/lexicon/en',
      75 => '/var/www/mnbsl/core/components/login/lexicon',
      76 => '/var/www/mnbsl/core/components/login/docs/readme.txt',
      77 => '/var/www/mnbsl/core/components/login/docs/changelog.txt',
      78 => '/var/www/mnbsl/core/components/login/docs/license.txt',
      79 => '/var/www/mnbsl/core/components/login/docs',
      80 => '/var/www/mnbsl/core/components/login/processors/register.php',
      81 => '/var/www/mnbsl/core/components/login/processors/update.profile.php',
      82 => '/var/www/mnbsl/core/components/login/processors',
      83 => '/var/www/mnbsl/core/components/login',
      84 => '/var/www/mnbsl/core/components',
    ),
  ),
  'e090c418213e07c2aeffd7518d4a2c58' => 
  array (
    'criteria' => 
    array (
      'key' => 'recaptcha.public_key',
    ),
    'object' => 
    array (
      'key' => 'recaptcha.public_key',
      'value' => '',
      'xtype' => 'textfield',
      'namespace' => 'recaptcha',
      'area' => 'reCaptcha',
      'editedon' => '0000-00-00 00:00:00',
    ),
  ),
  '7cde6ef4ee8bd41e698a189cbd3d396e' => 
  array (
    'criteria' => 
    array (
      'key' => 'recaptcha.private_key',
    ),
    'object' => 
    array (
      'key' => 'recaptcha.private_key',
      'value' => '',
      'xtype' => 'textfield',
      'namespace' => 'recaptcha',
      'area' => 'reCaptcha',
      'editedon' => '0000-00-00 00:00:00',
    ),
  ),
  'c6a981b06508a0c0e1b740983ad15f04' => 
  array (
    'criteria' => 
    array (
      'key' => 'recaptcha.use_ssl',
    ),
    'object' => 
    array (
      'key' => 'recaptcha.use_ssl',
      'value' => '',
      'xtype' => 'combo-boolean',
      'namespace' => 'recaptcha',
      'area' => 'reCaptcha',
      'editedon' => '0000-00-00 00:00:00',
    ),
  ),
);